# Generated by Django 5.2 on 2025-06-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['id'], 'verbose_name': 'Atendimentos', 'verbose_name_plural': 'Atendimentos'},
        ),
    ]
